"""add 1to1 relationship between comment and exercise

Revision ID: 1f650f4a252d
Revises: b2d994f3adec
Create Date: 2023-10-06 04:25:40.336398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f650f4a252d'
down_revision = 'b2d994f3adec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comments_exercise_id_exercises'), 'exercises', ['exercise_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_exercise_id_exercises'), type_='foreignkey')
        batch_op.drop_column('exercise_id')

    # ### end Alembic commands ###
