"""modified one-one, forgot exercise_id on Rating table

Revision ID: fd200293d998
Revises: 7e3dbbfe7793
Create Date: 2023-10-04 11:55:55.584931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd200293d998'
down_revision = '7e3dbbfe7793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_ratings_exercise_id_exercises'), 'exercises', ['exercise_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ratings_exercise_id_exercises'), type_='foreignkey')
        batch_op.drop_column('exercise_id')

    # ### end Alembic commands ###
